
# Site settings
title: A Blog by Emily 
description: A starter site
baseurl: "/blog" # folder where your site lives, e.g. /blog - needs to start with a slash
url: "http://emilyvictoria.github.io" # the base hostname & protocol for your site, e.g. http://hostname.domain.com

# Build settings
markdown: kramdown

defaults:  
  # template for pages unless an alternative is specified
  - scope:
      path: ""
    values:
      layout: "default"
